### ISSUE TITLE
[Request] Would be nice to support nested/2nd level tabs for more advanced settings pages

### ISSUE THREAD

**Issue by pgroot91** [stevegrunwell/wp-admin-tabbed-settings-pages#17]
Would be awesome to have support for nested settings pages / tabs for more advanced settings pages.

![image](https://user-images.githubusercontent.com/6934501/96374593-e670de80-1173-11eb-8145-2dd3fafc2af7.png)

**Comment by stevegrunwell** [comment]
While it's certainly _technically_ possible, I'm concerned about the usability implications.

The conventions of [the WordPress Settings API](https://developer.wordpress.org/plugins/settings/settings-api/) are such that we have a hierarchy of pages > sections > fields. Under the tabbed model, each section corresponds to a single tab.

While it would _technically_ be possible to nest tabs, this feels like an edge-case that doesn't meet [WordPress core's 80/20 view on functionality](https://wordpress.org/about/philosophy/#clean).

I'll also confess this also feels like a bad user experience (or at least one ripe for abuse) — if a plugin has this many settings, it probably makes sense to break them up into separate pages and/or longer settings screens.

The only plugin that immediately comes to mind that has enough settings to really benefit from this would be WooCommerce, which already uses a second level of tabs for select pages; I don't know that their approach is best, but they also contain all of the settings for an entire ecommerce platform:

![The WooCommerce tax settings screen, with multiple levels of tabs](https://user-images.githubusercontent.com/233836/97032295-94dba180-152f-11eb-80b2-17abbfc020f7.png)

I'm happy to revisit this down the line (especially if the code as proposed gets accepted into core), but I don't think this is something to pursue in the initial core proposal.
